server:
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
  port: 8086
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  elasticsearch:
    rest:
      uris: 127.0.0.1.9200
      password:

  datasource:
    # 数据库连接配置
    url: jdbc:mysql://localhost/learndemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    # 初始化大小，最小，最大配置
    druid:
      # 配置获取连接等待超时的时间
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,wall,stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      filter:
        stat:
          slow-sql-millis: 5000
      valid-connection-checker-class-name: com.alibaba.druid.pool.vendor.MSSQLValidConnectionChecker

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

mybatis-plus:
  # MyBatis 配置文件位置，如果您有单独的 MyBatis 配置，请将其路径配置到 configLocation 中。
  # config-location: classpath:mybatis-config.xml
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法
  mapper-locations: classpath*:mapper/*Mapper.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:  top.cloudos.**.entity
  #  # 配置扫描通用枚举 # 支持统配符 * 或者 ; 分割
  #  type-enums-package: com.abbottliu.sys.enums,com.abbottliu.enums
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  check-config-location: false
  #  ExecutorType.SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句（PreparedStatement）
  #  ExecutorType.REUSE：该执行器类型会复用预处理语句（PreparedStatement）
  #  ExecutorType.BATCH：该执行器类型会批量执行所有的更新语句
  executor-type: simple
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    # 配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: null
  global-config:
    db-config:
      # 数据库类型,默认值为未知的数据库类型
      # db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: true
